# Generated by Django 3.1.7 on 2021-05-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'suscribed_user',
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
