# Generated by Django 3.1.7 on 2021-05-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
